function iladata1 = importfile2(filename, dataLines)
%IMPORTFILE2 Import data from a text file
%  ILADATA1 = IMPORTFILE2(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a string array.
%
%  ILADATA1 = IMPORTFILE2(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  iladata1 = importfile2("C:\p\KR47\iladata.csv", [3, Inf]);
%
%  See also READMATRIX.
%
% Auto-generated by MATLAB on 24-May-2026 23:39:14

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 52);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_m0", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__1", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__2", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__3", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_m1", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__4", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__5", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__6", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_m2", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__7", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__8", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__9", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_m3", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_1", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_2", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_3"];
opts.SelectedVariableNames = ["usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_m0", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__1", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__2", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__3", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_m1", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__4", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__5", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__6", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_m2", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__7", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__8", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__9", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_m3", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_1", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_2", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_3"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_m0", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__1", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__2", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__3", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_m1", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__4", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__5", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__6", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_m2", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__7", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__8", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__9", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_m3", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_1", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_2", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_3"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_m0", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__1", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__2", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__3", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_m1", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__4", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__5", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__6", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_m2", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__7", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__8", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0__9", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_m3", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_1", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_2", "usp_rf_data_converter_0_ex_iex_designusp_rf_data_converter_0_3"], "EmptyFieldRule", "auto");

% Import the data
iladata1 = readmatrix(filename, opts);

end